/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.PromotionStatisticsBUS;
import POJO.PromotionStatisticsPOJO;
import POJO.PromotionTopsPOJO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bachl
 */
public class ViewTopsInPromotionFrame extends javax.swing.JFrame {

    private int totalRevenue;
    String typeChooser;
    private final int kTops = 10;
    
    DefaultTableModel tableModel = new DefaultTableModel() {
    //disable to edit table
    public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };
    /**
     * Creates new form ViewTopsInPromotionFrame
     */
    public ViewTopsInPromotionFrame() {
        initComponents();
        
        this.totalRevenue = 0;
        this.typeChooser = "";
        
        this.setLocationRelativeTo(null);
    }
    
    private void initTableViewTopOrders() {
        String []cols = new String[]{"ID Promotion", "ID", "Sum Cost"};
        tableModel.setColumnIdentifiers(cols);
        tableModel.setRowCount(0);
        
        tableViewTops.setModel(tableModel);
    }
    
    private void initTableViewTopCustomersOrBooks() {
        String []cols = new String[]{"ID Promotion", "ID", "Name", "Sum Cost"};
        tableModel.setColumnIdentifiers(cols);
        tableModel.setRowCount(0);
        
        tableViewTops.setModel(tableModel);
    }
        
    private void fillTableViewTops(List<PromotionTopsPOJO> promotionTops) {
        totalRevenue = 0;
        tableModel.setRowCount(0);
        
        for(int i = 0; i < promotionTops.size(); i++){
            String idPromotion = promotionTops.get(i).getIdPromotion();
            String id = promotionTops.get(i).getId();
            String name = promotionTops.get(i).getName();
            int sumCost = promotionTops.get(i).getSumCost();
            
            this.totalRevenue += sumCost;
           
            if(this.typeChooser.equals("order"))
                tableModel.addRow(new String[]{idPromotion, id, "" + sumCost});
            else if(this.typeChooser.equals("customer") || this.typeChooser.equals("book"))
                tableModel.addRow(new String[]{idPromotion, id, name, "" + sumCost});
        }
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewTops = new javax.swing.JTable();
        btnViewTopKOrders = new javax.swing.JButton();
        btnViewTopKBooks = new javax.swing.JButton();
        btnViewTopKCustomers = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tops Orders");

        tableViewTops.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        tableViewTops.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableViewTops.setRowHeight(35);
        jScrollPane1.setViewportView(tableViewTops);

        btnViewTopKOrders.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewTopKOrders.setText("Top 10 orders");
        btnViewTopKOrders.setPreferredSize(new java.awt.Dimension(195, 40));
        btnViewTopKOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTopKOrdersActionPerformed(evt);
            }
        });

        btnViewTopKBooks.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewTopKBooks.setText("Top 10 books");
        btnViewTopKBooks.setPreferredSize(new java.awt.Dimension(195, 40));
        btnViewTopKBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTopKBooksActionPerformed(evt);
            }
        });

        btnViewTopKCustomers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnViewTopKCustomers.setText("Top 10 customers");
        btnViewTopKCustomers.setPreferredSize(new java.awt.Dimension(195, 40));
        btnViewTopKCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTopKCustomersActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(115, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewTopKOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewTopKCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViewTopKBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewTopKOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTopKBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewTopKCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTopKCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTopKCustomersActionPerformed
        // TODO add your handling code here:
        this.typeChooser = "customer";
        PromotionStatisticsBUS bus = new PromotionStatisticsBUS();
        List<PromotionTopsPOJO> promotionTops = bus.getTopKCustomers(kTops);
        
        initTableViewTopCustomersOrBooks();
        if(promotionTops != null)
            fillTableViewTops(promotionTops);
    }//GEN-LAST:event_btnViewTopKCustomersActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewTopKOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTopKOrdersActionPerformed
        // TODO add your handling code here:
        this.typeChooser = "order";
        PromotionStatisticsBUS bus = new PromotionStatisticsBUS();

        List<PromotionTopsPOJO> promotionTops = bus.getTopKOrders(kTops);
        initTableViewTopOrders();
        
        if(promotionTops != null)
            fillTableViewTops(promotionTops);
    }//GEN-LAST:event_btnViewTopKOrdersActionPerformed

    private void btnViewTopKBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTopKBooksActionPerformed
        // TODO add your handling code here:
        this.typeChooser = "book";
        PromotionStatisticsBUS bus = new PromotionStatisticsBUS();
        List<PromotionTopsPOJO> promotionTops = bus.getTopKBooks(kTops);
        initTableViewTopCustomersOrBooks();
        fillTableViewTops(promotionTops);
    }//GEN-LAST:event_btnViewTopKBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTopsInPromotionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTopsInPromotionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTopsInPromotionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTopsInPromotionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTopsInPromotionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewTopKBooks;
    private javax.swing.JButton btnViewTopKCustomers;
    private javax.swing.JButton btnViewTopKOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableViewTops;
    // End of variables declaration//GEN-END:variables
}
